- name: Send email to students with inventory attached
  delegate_to: localhost
  sendgrid:
    username: "{{ sendgrid_user | default(omit) }}"
    password: "{{ sendgrid_pass | default(omit) }}"
    api_key: "{{ sendgrid_api_key | default(omit) }}"
    subject: "[Ansible] Instructor Inventory Details"
    body: |
          Attached is the Ansible inventory to be used for training.<br>
          Please check your ability to connect to each of the hosts via ssh.<br>
          <br>
    to_addresses: "{{ instructor_email }}"
    html_body: yes
    from_address: "{{ instructor_email }}"
    attachments:
      - "instructor_inventory.txt"
  when: email_instructor
  tags:
    - email_instructor
